{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous"},"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","title":"UserError.alreadyAnonymous","roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"platforms":["macOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous","title":"UserError.alreadyAnonymous","role":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth":{"title":"RxFireAuth","abstract":[],"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","url":"\/documentation\/rxfireauth"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"navigatorTitle":[{"text":"UserError","kind":"identifier"}],"title":"UserError","url":"\/documentation\/rxfireauth\/usererror","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserError"}]}}}