{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alreadyAnonymous"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"]}],"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"title":"UserError.alreadyAnonymous","modules":[{"name":"RxFireAuth"}],"externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","role":"symbol","symbolKind":"case"},"abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"kind":"symbol","references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","title":"UserError.alreadyAnonymous","abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"role":"symbol","url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous","kind":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","abstract":[],"role":"collection","title":"RxFireAuth","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","type":"topic","kind":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"title":"UserError","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","type":"topic","abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"navigatorTitle":[{"kind":"identifier","text":"UserError"}],"role":"symbol","url":"\/documentation\/rxfireauth\/usererror","kind":"symbol"}}}