{"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"RxFireAuth"}],"role":"symbol","symbolKind":"case","externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","title":"UserError.alreadyAnonymous","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"alreadyAnonymous","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous"},"kind":"symbol","abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"type":"topic","url":"\/documentation\/rxfireauth\/usererror","role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserError"}],"abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"type":"text","text":" implementations."}],"title":"UserError","navigatorTitle":[{"kind":"identifier","text":"UserError"}],"kind":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"type":"topic","role":"symbol","url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"kind":"symbol","title":"UserError.alreadyAnonymous"},"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","type":"topic","url":"\/documentation\/rxfireauth","kind":"symbol","title":"RxFireAuth","role":"collection","abstract":[]}}}