{"metadata":{"title":"UserError.alreadyAnonymous","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"alreadyAnonymous","kind":"identifier"}],"modules":[{"name":"RxFireAuth"}],"roleHeading":"Case","externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","symbolKind":"case"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous"},"abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"title":"UserError.alreadyAnonymous","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"kind":"symbol","abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"type":"topic","url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous"},"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","title":"RxFireAuth","type":"topic","abstract":[]},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"type":"topic","url":"\/documentation\/rxfireauth\/usererror","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"type":"text","text":" implementations."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserError"}],"title":"UserError","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UserError","kind":"identifier"}]}}}