{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"]}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","interfaceLanguage":"swift"},"metadata":{"externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","role":"symbol","modules":[{"name":"RxFireAuth"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"UserError.alreadyAnonymous"},"abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserError"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserError"}],"url":"\/documentation\/rxfireauth\/usererror","title":"UserError","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"},"doc://RxFireAuth/documentation/RxFireAuth":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","url":"\/documentation\/rxfireauth","type":"topic","title":"RxFireAuth"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"title":"UserError.alreadyAnonymous","abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"role":"symbol"}}}