{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"]}],"abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"title":"UserError.alreadyAnonymous","roleHeading":"Case","externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","modules":[{"name":"RxFireAuth"}],"role":"symbol"},"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"alreadyAnonymous","kind":"identifier"}],"platforms":["macOS"]}],"kind":"declarations"}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"url":"\/documentation\/rxfireauth\/usererror","role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UserError","kind":"identifier"}],"type":"topic","title":"UserError","kind":"symbol","navigatorTitle":[{"text":"UserError","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","kind":"symbol","role":"collection","title":"RxFireAuth","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","type":"topic","abstract":[]},"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","title":"UserError.alreadyAnonymous","kind":"symbol","role":"symbol","abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous"}}}