{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"metadata":{"modules":[{"name":"RxFireAuth"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"role":"symbol","externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","roleHeading":"Case","symbolKind":"case","title":"UserError.alreadyAnonymous"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous"},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"type":"text","text":" implementations."}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","navigatorTitle":[{"text":"UserError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UserError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror","title":"UserError"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"alreadyAnonymous","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"UserError.alreadyAnonymous","abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous"},"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","type":"topic","kind":"symbol","title":"RxFireAuth","abstract":[],"url":"\/documentation\/rxfireauth"}}}