{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"UserError.invalidUpdate","externalID":"s:10RxFireAuth9UserErrorO13invalidUpdateyA2CmF","modules":[{"name":"RxFireAuth"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidUpdate"}],"symbolKind":"case","roleHeading":"Case"},"sections":[],"abstract":[{"text":"The update cannot be performed because of invalid data.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidUpdate","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/invalidupdate"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","abstract":[{"text":"Errors thrown by  ","type":"text"},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}],"navigatorTitle":[{"text":"UserError","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserError"}],"title":"UserError","type":"topic","url":"\/documentation\/rxfireauth\/usererror"},"doc://RxFireAuth/documentation/RxFireAuth":{"title":"RxFireAuth","url":"\/documentation\/rxfireauth","kind":"symbol","type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","abstract":[],"role":"collection"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/invalidUpdate":{"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror\/invalidupdate","type":"topic","abstract":[{"text":"The update cannot be performed because of invalid data.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidUpdate","kind":"identifier"}],"title":"UserError.invalidUpdate","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","role":"symbol"}}}