{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"networkError","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError"},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"metadata":{"title":"UserError.networkError","externalID":"s:10RxFireAuth9UserErrorO07networkE0yA2CmF","symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"networkError","kind":"identifier"}],"modules":[{"name":"RxFireAuth"}]},"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/networkerror"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"An error occurred while reaching Firebase servers."}],"sections":[],"references":{"doc://RxFireAuth/documentation/RxFireAuth":{"kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","type":"topic","title":"RxFireAuth","abstract":[],"url":"\/documentation\/rxfireauth","role":"collection"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"title":"UserError","kind":"symbol","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}],"role":"symbol","url":"\/documentation\/rxfireauth\/usererror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserError"}],"type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","navigatorTitle":[{"text":"UserError","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth/UserError/networkError":{"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkError"}],"title":"UserError.networkError","url":"\/documentation\/rxfireauth\/usererror\/networkerror","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError","abstract":[{"type":"text","text":"An error occurred while reaching Firebase servers."}],"type":"topic"}}}