{"metadata":{"title":"UserError.networkError","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"networkError","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"externalID":"s:10RxFireAuth9UserErrorO07networkE0yA2CmF","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"An error occurred while reaching Firebase servers."}],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"sections":[],"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/networkerror"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","title":"RxFireAuth","type":"topic","abstract":[]},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"type":"topic","url":"\/documentation\/rxfireauth\/usererror","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"type":"text","text":" implementations."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserError"}],"title":"UserError","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UserError","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth/UserError/networkError":{"title":"UserError.networkError","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"kind":"symbol","abstract":[{"type":"text","text":"An error occurred while reaching Firebase servers."}],"type":"topic","url":"\/documentation\/rxfireauth\/usererror\/networkerror"}}}